stages:
  - test
  - publish
  # - deploy-alpha

test:
  # image: engineerball/python37-opencv453:1.0.0 # or another arbitrary docker image
  image: tiangolo/uvicorn-gunicorn-fastapi:python3.8
  stage: test
  script:
    # - apk add python3-dev gcc g++ libffi-dev openssl-dev make
    - pip install -r requirements-dev.txt
    - nosetests --with-coverage --cover-erase --cover-package=./ --cover-html tests
    - coverage report
  artifacts:
    paths:
      - cover/
  coverage: '/TOTAL\s+\d+\s+\d+\s+(\d+%)/'

publish-image:
  stage: publish
  dependencies:
    - test
  image:
    name: gcr.io/kaniko-project/executor:v1.6.0-debug
    entrypoint: [""]

  # When using dind, it's wise to use the overlayfs driver for
  # improved performance.
  variables:
    GOOGLE_APPLICATION_CREDENTIALS: /kaniko/config.json
    GCP_PROJECT_ID: $GCP_PROJECT_ID
    IMAGE_NAME: $IMAGE_NAME
  script:
    - echo $GCLOUD_SERVICE_KEY | tee /kaniko/config.json
    - /kaniko/executor --context $CI_PROJECT_DIR --dockerfile ./Dockerfile --destination gcr.io/$GCP_PROJECT_ID/$IMAGE_NAME:$(echo $CI_COMMIT_SHA | cut -c1-8) --destination gcr.io/$GCP_PROJECT_ID/$IMAGE_NAME:$(echo $CI_COMMIT_TAG | cut -d 'v' -f 2)
  only:
    - tags


# deploy-alpha:
#   stage: deploy-alpha
#   image: alpine:3.8
#   before_script:
#     - apk add --no-cache openssh git curl bash coreutils
#     - curl -s "https://raw.githubusercontent.com/kubernetes-sigs/kustomize/master/hack/install_kustomize.sh"  | bash
#     - mv kustomize /usr/local/bin/
#     - eval $(ssh-agent -s)
#     - echo "$DEVOPS_SSH_KEY" | tr -d '\r' | ssh-add -
#     - mkdir -p ~/.ssh
#     - chmod 700 ~/.ssh
#     - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'
#     - ssh -T git@gitlab.com
#     - git config --global user.name "${DEVOPS_USER_NAME}"
#     - git config --global user.email "${DEVOPS_USER_EMAIL}"
#     - git config --global push.followTags true

#   script:
#     - IMAGE_TAG=$(echo $CI_COMMIT_TAG | cut -d 'v' -f 2)
#     - git clone "git@gitlab.com:gatewayserviceth/ocr/face-recognition-ms-deployment.git"
#     - git checkout -B master
#     - cd face-recognition-ms-deployment/alpha
#     - kustomize edit set image gcr.io/$GCP_PROJECT_ID/$IMAGE_NAME:$IMAGE_TAG
#     - cat kustomization.yaml
#     - cd ../
#     - 'git commit -am "ci: update image to alpha-$IMAGE_TAG"'
#     - git tag -a -m "New release available - alpha-$IMAGE_TAG" alpha-$IMAGE_TAG
#     - git push origin master
#     - git push origin alpha-$IMAGE_TAG
#   only:
#     - tags